export const mockProducts = [
  {
    id: 1,
    title: 'Gypsum & Cement Boards',
    slug: 'gypsum-cement-boards',
    shortDesc: 'Regular, Fire-rated, Moisture-resistant, and Specialty boards from Gypsemna, Knauf, Gyproc, UMI',
    category: 'Building Materials',
    image: '/images/gypsum-board.jpg',
    featured: true,
    icon: '🏗️',
  },
  {
    id: 2,
    title: 'Ceiling Tiles & Profiles',
    slug: 'ceiling-tiles-profiles',
    shortDesc: 'Gypsum, Vinyl, Acoustic, and Metal ceiling systems from Skyline, USG, Danoline, Rockfon',
    category: 'Ceiling Systems',
    image: '/images/ceiling-tiles.jpg',
    featured: true,
    icon: '🏠',
  },
  {
    id: 3,
    title: 'Valeri Water Pumps',
    slug: 'valeri-water-pumps',
    shortDesc: 'Our exclusive UAE brand designed for efficiency, durability, and performance',
    category: 'Water Solutions',
    image: '/images/valeri-pumps.jpg',
    featured: true,
    icon: '💧',
  },
  {
    id: 4,
    title: 'Thermal & Acoustic Insulation',
    slug: 'thermal-acoustic-insulation',
    shortDesc: 'Rockwool, Glass Wool, and Phenolic Foam for construction, marine, and industrial applications',
    category: 'Insulation',
    image: '/images/insulation.jpg',
    featured: true,
    icon: '🔥',
  },
  {
    id: 5,
    title: 'Construction Accessories & Tools',
    slug: 'construction-accessories-tools',
    shortDesc: 'Channels, Profiles, Screws, Tapes, Sealants, and Metal Beads for complete construction solutions',
    category: 'Accessories',
    image: '/images/accessories.jpg',
    featured: false,
    icon: '🔧',
  },
]

export const mockServices = [
  {
    id: 1,
    title: 'Building Materials Supply & Distribution',
    summary: 'Comprehensive construction materials and supplies across 7 UAE branches',
    icon: '🏗️',
  },
  {
    id: 2,
    title: 'Interior Fit-Out & Ceiling Works',
    summary: 'Custom-designed acoustic, decorative, and functional ceiling systems',
    icon: '🔧',
  },
  {
    id: 3,
    title: 'Thermal & Acoustic Insulation Solutions',
    summary: 'High-performance insulation materials for construction, marine, and industrial sectors',
    icon: '📋',
  },
  {
    id: 4,
    title: 'Water Pump Design, Sales & Service',
    summary: 'Valeri brand pumps designed for efficiency, durability, and performance',
    icon: '💧',
  },
  {
    id: 5,
    title: 'Healthcare & Aesthetic Treatments',
    summary: 'Excellence in aesthetic dermatology, dentistry, and wellness care at Carewell Clinics',
    icon: '🏥',
  },
  {
    id: 6,
    title: 'IT & Digital Transformation Solutions',
    summary: 'ERPNext, POS, and AI-based marketing tools for smarter business systems',
    icon: '💻',
  },
]

export const mockClients = [
  { id: 1, name: 'Client 1', logo: '/images/client1.png' },
  { id: 2, name: 'Client 2', logo: '/images/client2.png' },
  { id: 3, name: 'Client 3', logo: '/images/client3.png' },
  { id: 4, name: 'Client 4', logo: '/images/client4.png' },
  { id: 5, name: 'Client 5', logo: '/images/client5.png' },
  { id: 7, name: 'Client 6', logo: '/images/client6.png' },
  { id: 8, name: 'Client 7', logo: '/images/client6.png' },
  { id: 9, name: 'Client 8', logo: '/images/client6.png' },
  { id: 10, name: 'Client 9', logo: '/images/client6.png' },
  { id: 11, name: 'Client 10', logo: '/images/client6.png' },
  { id: 12, name: 'Client 11', logo: '/images/client6.png' },
  { id: 13, name: 'Client 12', logo: '/images/client6.png' },
  { id: 14, name: 'Client 13', logo: '/images/client6.png' },
]

export const mockSpecializedMaterials = [
  {
    id: 1,
    title: 'Fire Resistant Panels',
    slug: 'fire-resistant-panels',
    shortDesc: 'Advanced fire protection materials for construction safety',
    category: 'Safety Materials',
    applications: ['Commercial buildings', 'Industrial facilities', 'Residential complexes'],
    certifications: ['BS 476', 'EN 13501', 'ASTM E84'],
    image: '/images/fire-panels.jpg',
    featured: true,
  },
  {
    id: 2,
    title: 'Thermal Insulation Boards',
    slug: 'thermal-insulation-boards',
    shortDesc: 'High-performance thermal insulation for energy efficiency',
    category: 'Insulation',
    applications: ['Roofing systems', 'Wall insulation', 'Cold storage'],
    certifications: ['ISO 9001', 'EN 13165', 'ASTM C518'],
    image: '/images/thermal-insulation.jpg',
    featured: false,
  },
  {
    id: 3,
    title: 'Acoustic Panels',
    slug: 'acoustic-panels',
    shortDesc: 'Sound-absorbing panels for noise control',
    category: 'Insulation',
    applications: ['Auditoriums', 'Offices', 'Educational facilities'],
    certifications: ['ISO 354', 'ASTM C423', 'EN ISO 11654'],
    image: '/images/acoustic-panels.jpg',
    featured: true,
  },
  {
    id: 4,
    title: 'Waterproofing Membranes',
    slug: 'waterproofing-membranes',
    shortDesc: 'Premium waterproofing solutions for construction',
    category: 'Waterproofing',
    applications: ['Roofing', 'Basements', 'Tunnels'],
    certifications: ['EN 13956', 'ASTM D412', 'ISO 14001'],
    image: '/images/waterproofing.jpg',
    featured: false,
  },
  {
    id: 5,
    title: 'Corrosion Resistant Coatings',
    slug: 'corrosion-resistant-coatings',
    shortDesc: 'Advanced coatings for metal protection',
    category: 'Protective Coatings',
    applications: ['Oil & gas', 'Marine structures', 'Industrial equipment'],
    certifications: ['NACE', 'SSPC', 'ISO 12944'],
    image: '/images/corrosion-coatings.jpg',
    featured: true,
  },
  {
    id: 6,
    title: 'High-Strength Concrete Admixtures',
    slug: 'high-strength-concrete-admixtures',
    shortDesc: 'Specialized admixtures for superior concrete performance',
    category: 'Concrete Solutions',
    applications: ['High-rise buildings', 'Bridges', 'Precast elements'],
    certifications: ['EN 934', 'ASTM C494', 'BS 5075'],
    image: '/images/concrete-admixtures.jpg',
    featured: false,
  },
]

export const mockTestimonials = [
  {
    id: 1,
    name: 'Ahmed Al-Rashid',
    role: 'Project Manager',
    company: 'Dubai Construction Co.',
    quote: 'Al Namariq Group of Companies provided exceptional quality materials and support for our latest project.',
    rating: 5,
    photo: '/images/testimonial1.jpg',
  },
  {
    id: 2,
    name: 'Sarah Johnson',
    role: 'Operations Director',
    company: 'Gulf Industries Ltd.',
    quote: 'Their specialized materials exceeded our expectations in performance and reliability.',
    rating: 5,
    photo: '/images/testimonial2.jpg',
  },
]
